package com.onlinefood.entities;

public enum StatusType {
	
	PENDING,CONFIRMED,PREPARING,COOKING,READY_FOR_PICKUP,OUT_FOR_DELIVERY,DELIVERED,CANCELLED,DELAYED,REFUNDED,FAILED,COMPLETED,RETURNED,PARTIAL_DELIVERY,PENDING_PAYMENT,ON_HOLD,REVIEW,ARCHIVE

}
